feat(netherlands): :tada: adding netherlands
jimmyheller/tech-immigrants pull request #2
Opened 2021-10-10 11:57 UTC by amin-setayeshfar

adding netherlands and some faq from messages in group(s)

2021-10-10 17:40 UTC, jimmyheller requested changes
فایل‌هایی که تو سیستم خودت هست  مثل ds_store نباید کامیت بشن. 
همچنین اگر جایی از متن شخصی هست مثل (خونه ما) بهتره که generalize بشه که قابل تعمیم باشه.

2021-10-10 17:40 UTC, jimmyheller commented on .vscode/settings.json
> +}
این فایل لازم نیست کامیت بشه

2021-10-10 17:40 UTC, jimmyheller commented on netherlands/readme.md
> +# Netherlands, Highly Skilled Immigrant FAQ
به نظرم به طور کامل فارسی بنویسیم و در نهایت از تگ‌های انگلیسی استفاده کنیم.

2021-10-10 18:25 UTC, amin-setayeshfar commented on .vscode/settings.json
> +}
done

2021-10-10 21:04 UTC, jimmyheller commented on .gitignore
> +Thumbs.db
please remove your .gitignore

2021-10-10 21:05 UTC, jimmyheller commented on netherlands/readme.md
> +https://www.reddit.com/r/recruitinghell/comments/puivlb/have_you_been_interviewing_for_anywhere_else/?utm_medium=android_app&utm_source=share
still mixed language

2021-10-11 18:05 UTC, jimmyheller approved these changes

2021-10-11 18:05 UTC, merged